services:
  sync-server:
    image: ghcr.io/automerge/automerge-repo-sync-server:main
    ports:
      - "8080:8080"
    volumes:
      - ${SYNC_DATA_DIR:-./data/dev/sync}:/data
    environment:
      - PORT=8080
      - DATA_DIR=/data
